In [1]:
import pandas as pd
import numpy as np
import ast
import re

In [2]:
df = pd.read_csv("df_EDA_narrow.csv")

In [3]:
df_exploded = pd.read_csv("EDA_explod_narrow.csv")

In [47]:
core_skills = [

    # programming
    'python',
    'sql',
    'r',

    # spreadsheets / BI
    'excel',
    'power bi',
    'tableau',

    # data libraries
    'pandas',
    'numpy',

    # machine learning
    'machine learning',
    'deep learning',
    'nlp',
    'natural language processing',

    # cloud / big data
    'aws',
    'spark',
    'hadoop',

    # analytics concepts
    'data analysis',
    'data analytics',
    'data visualization',
    'data modeling',
    'statistics',

    # databases
    'sql server',
    'postgresql',
    'mysql',

    # engineering / workflow
    'etl',
    'data warehousing',

]

In [48]:
df_skill_focus = df_exploded[
    df_exploded['skills'].isin(core_skills)
]

In [49]:
job_cols = [
    'company',
    'job_tittle',
    'location',
    'salary_mid'
]

df_skill_focus = (
    df_skill_focus
    .drop_duplicates(subset=job_cols + ['skills'])
)

In [50]:
skill_counts = (
    df_skill_focus['skills']
    .value_counts()
)

valid_skills = skill_counts[
    skill_counts >= 5
].index

df_skill_focus = df_skill_focus[
    df_skill_focus['skills'].isin(valid_skills)
]

In [53]:
top_skills = (
    df_skill_focus['skills']
    .value_counts()
    .reset_index()
)

top_skills.columns = ['skill', 'job_count']

In [54]:
top_skills

                          skill  job_count
0                        python        664
1                           sql        644
2              machine learning        459
3                      power bi        407
4                 data analysis        316
5                       tableau        231
6                data analytics        167
7                         excel        159
8                 data modeling        157
9                           aws        145
10  natural language processing        135
11                            r        114
12                          etl         91
13                   statistics         79
14             data warehousing         75
15                        spark         74
16                       pandas         58
17                          nlp         34

In [55]:
total_jobs = df.shape[0]

top_skills['demand_pct'] = (
    top_skills['job_count'] / total_jobs * 100
).round(2)

In [56]:
total_jobs

1808

In [57]:
skill_salary = (
    df_skill_focus
    .groupby('skills')
    .agg(
        avg_salary=('salary_mid', 'mean'),
        median_salary=('salary_mid', 'median'),
        job_count=('skills', 'count')
    )
    .reset_index()
)

In [58]:
skill_salary

                         skills  avg_salary  median_salary  job_count
0                           aws   15.537931           12.5        145
1                 data analysis   10.027690            8.0        316
2                data analytics   11.159639            8.0        167
3                 data modeling   13.676282            8.0        157
4              data warehousing   10.666667            8.0         75
5                           etl   11.754396            8.0         91
6                         excel    7.307753            4.5        159
7              machine learning   15.358388           12.5        459
8   natural language processing   17.363889           12.5        135
9                           nlp   15.176471           12.5         34
10                       pandas   13.650862           12.5         58
11                     power bi   11.326663            8.0        407
12                       python   14.148567           12.5        664
13                            r   13.101770            8.0        114
14                        spark   11.722973            8.0         74
15                          sql   12.353227            8.0        644
16                   statistics   12.488924            8.0         79
17                      tableau   10.560714            8.0        231

In [52]:
# df_skill_focus.to_csv('df_skill_focus.csv', index = False)